name: adaspot

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - numpy
  - matplotlib
  - pip:
      - opencv-python
      - SoccerNet
      - tabulate
      - timm
      - tqdm
